name: Generate and Deploy XML

on:
  workflow_dispatch:  # ручний запуск
  schedule:
    - cron: '0 3 * * *'  # щодня о 03:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Generate XML
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        run: node generate-xml.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          keep_files: false
          force_orphan: true
          exclude_assets: '**'
          include_assets: 'output.xml'

